# Generated by Django 5.2.5 on 2025-09-28 18:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('institution', models.CharField(help_text='Name of your school/university', max_length=200, verbose_name='Educational Institution')),
                ('field_of_study', models.CharField(help_text='Your major or area of study', max_length=200, verbose_name='Field of Study')),
                ('academic_level', models.CharField(help_text='e.g., Bachelor, Master, PhD', max_length=100, verbose_name='Academic Level')),
                ('graduation_year', models.PositiveIntegerField(help_text='Year you expect to graduate', verbose_name='Expected Graduation Year')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, help_text='Your current GPA or grade average', max_digits=4, null=True, verbose_name='GPA/Grade')),
                ('cv_resume', models.FileField(help_text='Upload your CV or resume (PDF, DOC, DOCX)', upload_to='applications/cv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='CV/Resume')),
                ('cover_letter', models.FileField(blank=True, help_text='Upload your cover letter (optional)', upload_to='applications/cover_letters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Cover Letter')),
                ('transcript', models.FileField(blank=True, help_text='Upload your academic transcript (optional)', upload_to='applications/transcripts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Academic Transcript')),
                ('motivation_letter', models.TextField(help_text='Tell us why you want this internship and what you hope to achieve', verbose_name='Motivation Letter')),
                ('previous_experience', models.TextField(blank=True, help_text='Describe any relevant work or internship experience', verbose_name='Previous Experience')),
                ('skills', models.TextField(blank=True, help_text='List your relevant skills and competencies', verbose_name='Skills and Competencies')),
                ('available_start_date', models.DateField(help_text='When can you start the internship?', verbose_name='Available Start Date')),
                ('duration_months', models.PositiveIntegerField(help_text='How many months would you like to intern?', verbose_name='Preferred Duration (months)')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('intern_created', 'Intern Account Created')], default='pending', help_text='Current status of the application', max_length=20)),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='Review Date')),
                ('review_notes', models.TextField(blank=True, help_text='Admin notes about the application', verbose_name='Review Notes')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_intern', models.OneToOneField(blank=True, limit_choices_to={'role': 'intern'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to=settings.AUTH_USER_MODEL, verbose_name='Created Intern Account')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internships.internship', verbose_name='Desired Internship')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'Internship Application',
                'verbose_name_plural': 'Internship Applications',
                'ordering': ['-submitted_at'],
                'unique_together': {('email', 'internship')},
            },
        ),
    ]
