# Generated by Django 5.2.5 on 2025-09-28 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Skill Name')),
                ('category', models.CharField(blank=True, help_text='e.g., Programming, Design, Marketing', max_length=50, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internship position title', max_length=200, verbose_name='Title')),
                ('description', models.TextField(help_text='Detailed description of the internship', verbose_name='Description')),
                ('requirements', models.TextField(help_text='Skills and qualifications required', verbose_name='Requirements')),
                ('responsibilities', models.TextField(help_text='Main tasks and responsibilities', verbose_name='Responsibilities')),
                ('department', models.CharField(help_text='Department or team', max_length=200, verbose_name='Department')),
                ('location', models.CharField(help_text='Work location (city, country or remote)', max_length=200, verbose_name='Location')),
                ('internship_type', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('stipend', 'Stipend')], default='unpaid', max_length=20, verbose_name='Type')),
                ('duration', models.CharField(choices=[('1-3', '1-3 months'), ('3-6', '3-6 months'), ('6-12', '6-12 months'), ('12+', '12+ months')], default='3-6', max_length=10, verbose_name='Duration')),
                ('salary_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly amount in CFA', max_digits=10, null=True, verbose_name='Salary/Stipend Amount')),
                ('benefits', models.TextField(blank=True, help_text='Additional benefits offered', verbose_name='Benefits')),
                ('application_deadline', models.DateField(help_text='Last date to apply', verbose_name='Application Deadline')),
                ('start_date', models.DateField(help_text='When the internship is expected to start', verbose_name='Expected Start Date')),
                ('end_date', models.DateField(help_text='When the internship is expected to end', verbose_name='Expected End Date')),
                ('max_applicants', models.PositiveIntegerField(default=50, help_text='Maximum number of applications to accept', verbose_name='Maximum Applicants')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this internship is currently accepting applications', verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to feature this internship prominently', verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_internships', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_internships', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Supervisor')),
            ],
            options={
                'verbose_name': 'Internship',
                'verbose_name_plural': 'Internships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternshipSkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20, verbose_name='Required Level')),
                ('is_required', models.BooleanField(default=True, help_text='Whether this skill is required or preferred', verbose_name='Required')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='internships.internship')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_requirements', to='internships.internshipskill')),
            ],
            options={
                'verbose_name': 'Skill Requirement',
                'verbose_name_plural': 'Skill Requirements',
                'unique_together': {('internship', 'skill')},
            },
        ),
    ]
