# Generated by Django 5.2.5 on 2025-09-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='intern_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount intern pays for the internship (CFA)', max_digits=10, null=True, verbose_name='Intern Payment Amount'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='internship_type',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('stipend', 'Stipend'), ('paid_by_intern', 'Paid by Intern')], default='unpaid', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='salary_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly amount in CFA (for paid internships)', max_digits=10, null=True, verbose_name='Salary/Stipend Amount'),
        ),
    ]
